version: '3.8'
services:
  zookeeper_2:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper_2
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_2
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Alterado para 2
    depends_on:
      - zookeeper_2

